misc fixes changes
Signed-off-by: Rohit Yadav <rohit.yadav@shapeblue.com>

diff --git a/systemvm/patches/debian/config/etc/init.d/cloud-early-config b/systemvm/patches/debian/config/etc/init.d/cloud-early-config
--- a/systemvm/patches/debian/config/etc/init.d/cloud-early-config
+++ b/systemvm/patches/debian/config/etc/init.d/cloud-early-config
@@ -5,7 +5,7 @@
 # Required-Stop:     $local_fs
 # Default-Start:     S
 # Default-Stop:      0 6
-# Short-Description: configure according to cmdline
+# Short-Description: configures systemvm using cmdline
 ### END INIT INFO
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
@@ -125,30 +125,30 @@ get_boot_params() {
             log_it "${VPORT} not loaded, perhaps guest kernel is too old." && exit 2
           fi
 
-	      local factor=2
-	      local progress=1
-		  for i in {1..5}
-		  do
-	        while read line; do
-	          if [[ $line == cmdline:* ]]; then
-	            cmd=${line//cmdline:/}
+          local factor=2
+          local progress=1
+          for i in {1..5}
+          do
+            while read line; do
+              if [[ $line == cmdline:* ]]; then
+                cmd=${line//cmdline:/}
                 echo $cmd > /var/cache/cloud/cmdline
-	          elif [[ $line == pubkey:* ]]; then
-	            pubkey=${line//pubkey:/}
-	            echo $pubkey > /var/cache/cloud/authorized_keys
-	            echo $pubkey > /root/.ssh/authorized_keys
+              elif [[ $line == pubkey:* ]]; then
+                pubkey=${line//pubkey:/}
+                echo $pubkey > /var/cache/cloud/authorized_keys
+                echo $pubkey > /root/.ssh/authorized_keys
               fi
-	        done < $VPORT
-	        # In case of reboot we do not send the boot args again.
-	        # So, no need to wait for them, as the boot args are already set at startup
-	        if [ -s /var/cache/cloud/cmdline  ]
-	        then
+            done < $VPORT
+            # In case of reboot we do not send the boot args again.
+            # So, no need to wait for them, as the boot args are already set at startup
+            if [ -s /var/cache/cloud/cmdline  ]
+            then
               log_it "Found a non empty cmdline file. Will now exit the loop and proceed with configuration."
               break;
             fi
             sleep ${progress}s
             progress=$[ progress * factor ]
-		  done
+          done
           chmod go-rwx /root/.ssh/authorized_keys
           ;;
      vmware)
@@ -577,12 +577,12 @@ setup_common() {
   fi
   if [ -n "$ETH0_IP6" ]
   then
-	  setup_interface_ipv6 "0" $ETH0_IP6 $ETH0_IP6_PRELEN
+      setup_interface_ipv6 "0" $ETH0_IP6 $ETH0_IP6_PRELEN
   fi
   setup_interface "1" $ETH1_IP $ETH1_MASK $GW
   if [ -n "$ETH2_IP" ]
   then
-  	setup_interface "2" $ETH2_IP $ETH2_MASK $GW
+    setup_interface "2" $ETH2_IP $ETH2_MASK $GW
   fi
    
   echo $NAME > /etc/hostname
@@ -841,13 +841,6 @@ setup_apache2() {
   clean_ipalias_config
   setup_apache2_common
   local ip=$1
-
-  # Deprecated, functionality moved to Cs Python code
-  # [ -f /etc/apache2/sites-available/default ] && sed -i -e "s/<VirtualHost.*>/<VirtualHost $ip:80>/" /etc/apache2/sites-available/default
-  # [ -f /etc/apache2/sites-available/default-ssl ] && sed -i -e "s/<VirtualHost.*>/<VirtualHost $ip:443>/" /etc/apache2/sites-available/default-ssl
-  # [ -f /etc/apache2/ports.conf ] && sed -i -e "s/Listen .*:80/Listen $ip:80/g" /etc/apache2/ports.conf
-  # [ -f /etc/apache2/ports.conf ] && sed -i -e "s/Listen .*:443/Listen $ip:443/g" /etc/apache2/ports.conf
-  # [ -f /etc/apache2/ports.conf ] && sed -i -e "s/NameVirtualHost .*:80/NameVirtualHost $ip:80/g" /etc/apache2/ports.conf
 }
 
 setup_aesni() {
@@ -885,7 +878,7 @@ setup_router() {
         done
       fi
   else
-  	setup_common eth0 eth1
+    setup_common eth0 eth1
       if [ -n "$EXTRA_PUBNICS" ]
       then
         for((i = 2; i < 2 + $EXTRA_PUBNICS; i++))
@@ -1090,19 +1083,19 @@ setup_dhcpsrvr() {
 }
 
 setup_storage_network() {
-	if [ x"$STORAGE_IP" == "x" -o x"$STORAGE_NETMASK" == "x" ]
-	then
-		log_it "Incompleted parameters STORAGE_IP:$STORAGE_IP, STORAGE_NETMASK:$STORAGE_NETMASK, STORAGE_CIDR:$STORAGE_CIDR. Cannot setup storage network"
-		return
-	fi
-	
-	echo "" >> /etc/network/interfaces
-	echo "auto eth3" >> /etc/network/interfaces
-	
-	setup_interface "3" "$STORAGE_IP" "$STORAGE_NETMASK"
+    if [ x"$STORAGE_IP" == "x" -o x"$STORAGE_NETMASK" == "x" ]
+    then
+        log_it "Incompleted parameters STORAGE_IP:$STORAGE_IP, STORAGE_NETMASK:$STORAGE_NETMASK, STORAGE_CIDR:$STORAGE_CIDR. Cannot setup storage network"
+        return
+    fi
+
+    echo "" >> /etc/network/interfaces
+    echo "auto eth3" >> /etc/network/interfaces
+
+    setup_interface "3" "$STORAGE_IP" "$STORAGE_NETMASK"
     [ -n "$MTU" ] && ifconfig eth3 mtu $MTU && echo "  mtu $MTU" >> /etc/network/interfaces
-	#ip route add "$STORAGE_CIDR" via "$STORAGE_IP"
-	log_it "Successfully setup storage network with STORAGE_IP:$STORAGE_IP, STORAGE_NETMASK:$STORAGE_NETMASK, STORAGE_CIDR:$STORAGE_CIDR"
+    #ip route add "$STORAGE_CIDR" via "$STORAGE_IP"
+    log_it "Successfully setup storage network with STORAGE_IP:$STORAGE_IP, STORAGE_NETMASK:$STORAGE_NETMASK, STORAGE_CIDR:$STORAGE_CIDR"
 }
 
 setup_system_rfc1918_internal() {
@@ -1277,10 +1270,10 @@ EOF
 }
 
 change_password() {
-	if [ x"$VM_PASSWORD" != x"" ]
-	then
-		echo "root:$VM_PASSWORD" | chpasswd
-	fi
+    if [ x"$VM_PASSWORD" != x"" ]
+    then
+        echo "root:$VM_PASSWORD" | chpasswd
+    fi
 }
 
 start() {
@@ -1301,50 +1294,52 @@ start() {
          setup_router
          if [ -x /opt/cloud/bin/update_config.py ]
          then
-	         /opt/cloud/bin/update_config.py cmd_line.json
+             /opt/cloud/bin/update_config.py cmd_line.json
          fi
-	  ;;
+      ;;
      vpcrouter)
          [ "$NAME" == "" ] && NAME=vpcrouter
          setup_vpcrouter
          if [ -x /opt/cloud/bin/update_config.py ]
          then
-	         /opt/cloud/bin/update_config.py cmd_line.json
+             /opt/cloud/bin/update_config.py cmd_line.json
          fi
-	  ;;
+      ;;
      dhcpsrvr)
          [ "$NAME" == "" ] && NAME=dhcpsrvr
          setup_dhcpsrvr
          if [ -x /opt/cloud/bin/update_config.py ]
          then
-	         /opt/cloud/bin/update_config.py cmd_line.json
+             /opt/cloud/bin/update_config.py cmd_line.json
          fi
-	  ;;
+      ;;
      secstorage)
          [ "$NAME" == "" ] && NAME=secstorage
          setup_secstorage $hyp;
-	  ;;
+      ;;
      consoleproxy)
          [ "$NAME" == "" ] && NAME=consoleproxy
          setup_console_proxy $hyp;
-	  ;;
+      ;;
      elbvm)
          [ "$NAME" == "" ] && NAME=elb
          setup_elbvm
-	  ;;
+      ;;
      ilbvm)
          [ "$NAME" == "" ] && NAME=ilb
          setup_ilbvm
-	  ;;
+      ;;
      unknown)
          [ "$NAME" == "" ] && NAME=systemvm
          setup_default;
           ;;
   esac
-    if [ "$hyp" == "hyperv" ]; then
-    # eject the systemvm.iso
+
+  if [ "$hyp" == "hyperv" ]; then
+     # eject the systemvm.iso
      eject
   fi
+
   return 0
 }
 
@@ -1446,25 +1441,25 @@ for i in $CMDLINE
           ;;
       template)
         TEMPLATE=$VALUE
-      	;;
+        ;;
       sshonguest)
         SSHONGUEST=$VALUE
         ;;
       name)
-	    NAME=$VALUE
-	    ;;
+        NAME=$VALUE
+        ;;
       dhcprange)
         DHCP_RANGE=$(echo $VALUE | tr ':' ',')
-      	;;
+        ;;
       bootproto)
         BOOTPROTO=$VALUE 
-      	;;
+        ;;
       type)
-        TYPE=$VALUE	
-	    ;;
+        TYPE=$VALUE
+        ;;
       defaultroute)
-        DEFAULTROUTE=$VALUE	
-	;;
+        DEFAULTROUTE=$VALUE
+    ;;
       redundant_router)
         RROUTER=$VALUE
         ;;
@@ -1518,7 +1513,7 @@ done
 echo -e "\n\t}\n}" >> ${CHEF_TMP_FILE}
 if [ "$TYPE" != "unknown" ]
 then
-	mv ${CHEF_TMP_FILE} /var/cache/cloud/cmd_line.json
+    mv ${CHEF_TMP_FILE} /var/cache/cloud/cmd_line.json
 fi
 
 [ $ETH0_IP ] && LOCAL_ADDRS=$ETH0_IP
@@ -1529,37 +1524,37 @@ fi
 case "$1" in
 start)
 
-	log_action_begin_msg "Executing cloud-early-config"
-        log_it "Executing cloud-early-config"
-	if start; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
+    log_action_begin_msg "Executing cloud-early-config"
+    log_it "Executing cloud-early-config"
+    if start; then
+        log_action_end_msg $?
+    else
+        log_action_end_msg $?
+    fi
+    ;;
 
 stop)
-	log_action_begin_msg "Stopping cloud-early-config"
-        #Override old system's interface setting
-        setup_default;
-	log_action_end_msg 0
-	;;
+    log_action_begin_msg "Stopping cloud-early-config"
+    #Override old system's interface setting
+    setup_default;
+    log_action_end_msg 0
+    ;;
 
 force-reload|restart)
 
-	log_warning_msg "Running $0  is deprecated because it may not enable again some interfaces"
-	log_action_begin_msg "Executing cloud-early-config"
-	if start; then
-	    log_action_end_msg $?
-	else
-	    log_action_end_msg $?
-	fi
-	;;
+    log_warning_msg "Running $0  is deprecated because it may not enable again some interfaces"
+    log_action_begin_msg "Executing cloud-early-config"
+    if start; then
+        log_action_end_msg $?
+    else
+        log_action_end_msg $?
+    fi
+    ;;
 
 *)
-	echo "Usage: /etc/init.d/cloud-early-config {start|stop}"
-	exit 1
-	;;
+    echo "Usage: /etc/init.d/cloud-early-config {start|stop}"
+    exit 1
+    ;;
 esac
 
 exit 0
